version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Update Yarn repository key and configuration
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /usr/share/keyrings/yarn-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/yarn-archive-keyring.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list > /dev/null

      # Remove sbt repository if it's causing issues
      - rm -f /etc/apt/sources.list.d/sbt.list

      # Update APT repositories
      - apt-get update || apt-get update --fix-missing

  pre_build:
    commands:
      - echo "Executing pre-build steps"

  build:
    commands:
      - echo "Running Terraform commands"
      - terraform --version  # Check Terraform version for verification
      - terraform init       # Initialize Terraform (if needed)
      - terraform validate s3.tf  # Validate the Terraform configuration
      - terraform plan -out=tfplan -input=false s3.tf  # Create an execution plan
      - terraform apply -auto-approve tfplan  # Apply changes

  post_build:
    commands:
      - echo "Executing post-build steps"

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.cache/**/*'
