version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies or any setup tasks"

  pre_build:
    commands:
      - echo "Executing pre-build steps"

  build:
    commands:
      - echo "Executing build steps"

  post_build:
    commands:
      - echo "Executing post-build steps"

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.cache/**/*'

