version: 0.2

phases:
  pre_build:
    commands:
      - echo "Executing pre-build steps"
      - ./install-terraform.sh
      - ./configure-named-profile.sh
      - ./apply-terraform.sh

  build:
    commands:
      - echo "Executing build steps"
      - terraform init
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo "Executing post-build steps"

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.cache/**/*'
